### ISSUE TITLE
cant install lib

### ISSUE THREAD

**Issue by Luca-x64** [Attol8/istatapi#11]
hi, i cant install the lib "istat api" on fedora linux 36
![image](https://user-images.githubusercontent.com/86069272/221532052-4f02f36e-6694-4ebc-80df-aa43c3a60aef.png)

![image](https://user-images.githubusercontent.com/86069272/221532418-deb3d268-ae01-4d3b-b7ff-81eb4a60987d.png)
even on pypi.org i cant find this lib

**Comment by Attol8** [comment]
Hi @Luca-x64 thanks for your interest in the library. I still haven't configured the library on pypi.org due to not having a lot of time recently. I will do it today and let you know when you can `pip install istatapi`.

**Comment by Luca-x64** [comment]
oh ok no problem, i just wait ;)

**Comment by Attol8** [comment]
Hey @Luca-x64 , 

you can now `pip install istatapi` to install the library 

let me know if you have any feedback and feel free to modify the code and open a pull request on this project so I can review 😄  

The library is fully functional as it is, but In the next few days I am planning to make the library more usable by:

* Clean readme file style (known issue from nbdev)
* fix some minor bugs 
* refactor code in `base.ipynb`

**Comment by Luca-x64** [comment]
successful installation
