### ISSUE TITLE
SSLError: HTTPSConnectionPool

### ISSUE THREAD

**Issue by AndreaScotti01** [Attol8/istatapi#14]
I got this error, I hope this can help :)

My code:
`istat_available = istatapi.all_available()`

Error:
`HTTPSConnectionPool(host='sdmx.istat.it', port=443): Max retries exceeded with url: [/SDMXWS/rest/dataflow/IT1](https://file+.vscode-resource.vscode-cdn.net/SDMXWS/rest/dataflow/IT1) (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)')))`

**Comment by AndreaScotti01** [comment]
I'm getting this with my Ubuntu system with windows machine it gives me a warning instead.

Warning:

`Unverified HTTPS request is being made to host 'sdmx.istat.it'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings`

**Comment by Attol8** [comment]
Hi @AndreaScotti01 thanks for opening this issue. I will try to replicate and fix :) I had this issue before and it might require migrating the requests to another endpoint as istat changed it recently.

**Comment by AndreaScotti01** [comment]
I hope this can help , I was using python 3.10.6 on Ubuntu and those were the libraries I had in that Venv.

[requirements.txt](https://github.com/Attol8/istatapi/files/11129911/requirements.txt)
