### ISSUE TITLE
wrong data inference with annual frequency

### ISSUE THREAD

**Issue by priolap** [Attol8/istatapi#16]
Hello,

I've just noticed that these lines of code:

if "TIME_PERIOD" in df.columns:
        df["TIME_PERIOD"] = pd.to_datetime(
            df["TIME_PERIOD"], infer_datetime_format=True
        )
        df = df.sort_values(by=["TIME_PERIOD"])

are wrong, because when data frequency is annual the TIME_PERIOD field is populated only by the year, i.e. "2000"
>>> df["TIME_PERIOD"] 
Out[119]: 
0       2000
1       2005
2       2013
3       2000
4       2005

>>> pd.to_datetime( df["TIME_PERIOD"], infer_datetime_format=True )
Out[120]: 
0      1970-01-01 00:00:00.000002000
1      1970-01-01 00:00:00.000002005
2      1970-01-01 00:00:00.000002013
3      1970-01-01 00:00:00.000002000
4      1970-01-01 00:00:00.000002005

this is fixed by deleting the last line of code.

**Comment by Attol8** [comment]
Hi @priolap sorry for taking forever to fix this issue. It should now be fixed by #20 . Let me know if you check your code again to see if it now works!
