### ISSUE TITLE
Error 400 when filtering with a list

### ISSUE THREAD

**Issue by Batchounet** [Attol8/istatapi#23]
Hi there,

When I try running your demonstration code : 
```
from istatapi import discovery, retrieval

ds = discovery.DataSet(dataflow_identifier="139_176")


freq = "M" #monthly frequency
tipo_dato = ["ISAV", "ESAV"] #imports and exports seasonally adjusted data
paese_partner = "WORLD" #trade with all countries

ds.set_filters(freq = freq, tipo_dato = tipo_dato, paese_partner = paese_partner)
trade_df = retrieval.get_data(ds)
trade_df.head()
```
it returns me an error 400, bad request. However, when I try with `ds.set_filters(freq = freq, paese_partner = paese_partner)`, i get the dataframe correctly. Same result with another example : 
`ds = discovery.DataSet(dataflow_identifier="22_315")
freq = 'A'
sesso = '9'
itter107 = ['IT', 'ITG', 'ITF']

ds.set_filters(freq = freq, itter107 = itter107, sesso = sesso)
df =  retrieval.get_data(ds)`
doesnt work, while 
```
ds = discovery.DataSet(dataflow_identifier="22_315")
freq = 'A'
sesso = '9'

ds.set_filters(freq = freq, sesso = sesso)
df =  retrieval.get_data(ds)
```
does.  I suppose there is an issue with the way filtering with a list is handled. Do you have any idea how I could solve that ?

It might be known to you, but I also get this warning : anaconda3\Lib\site-packages\istatapi\retrieval.py:29: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df["TIME_PERIOD"] = pd.to_datetime(
  
ps : thanks for the work. I am a begginner and I am very happy to find such an api instead of having to struggle with istat or their enpoint

**Comment by Attol8** [comment]
Hey, thanks for pointing out this issue. I have added a test in #26 

```python
#initiate the dataset
dataset = DataSet(dataflow_identifier="139_176")

#define some filters
freq = "M"
tipo_dato=["ISAV", "ESAV"]
paese_partner="WORLD"

#set filters
dataset.set_filters(freq=freq, tipo_dato=tipo_dato, paese_partner=paese_partner)
#return dataset
trade_df = get_data(dataset)
trade_df.head()
test_eq(trade_df['FREQ'].unique(), ['M'])
test_eq(trade_df['TIPO_DATO'].unique().sort(), ["ISAV", "ESAV"].sort())
test_eq(trade_df['PAESE_PARTNER'].unique().sort(), ["WORLD"].sort())
test_eq(type(trade_df['TIME_PERIOD'].iloc[0]), pd._libs.tslibs.timestamps.Timestamp)
```

I can confirm this works
