### ISSUE TITLE
Not able to download latest dataset for negotiated wages

### ISSUE THREAD

**Issue by OtavioEsper** [Attol8/istatapi#25]
Code:
ds = discovery.DataSet(dataflow_identifier = "155_358")
ds.dimensions_info()

freq = 'm'
ateco_2007 = '10'
qual_prof = '10'
tip_aggr1 = 'WAGE_E_2'

ds.set_filters(FREQ = freq, ATECO_2007 = ateco_2007, QUAL_PROF = qual_prof, TIP_AGGR1 = tip_aggr1)

df3 = retrieval.get_data(ds)

This retrieves a data set, base 2015, that only has data up until December 2023. The latest data (which is retrievable in the Istat website by using tip_aggr1 = 'WAGE_E_2021') yields an empty dataframe

**Comment by Attol8** [comment]
Hi @OtavioEsper , unluckily `WAGE_E_2021` is a value that is not present in the `available_values` for DataSet `155_358`. Honestly I am not sure why and cannot investigate further right now. I have added a test in #26 to confirm that the value is not present
